# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
radarr:
  radarr:
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    media_naming:
      folder: plex
      movie:
        rename: true
        standard: default

    include:
      # Comment out any of the following includes to disable them
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-hd-bluray-web
      - template: radarr-custom-formats-hd-bluray-web

    custom_formats:
      # =================================
      # HD Bluray + WEB
      # =================================
      # Movie Versions
      - trash_ids:
      # Uncomment any of the following lines to prefer these movie versions
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        assign_scores_to:
          - name: HD Bluray + WEB

      # Optional
      - trash_ids:
          - e7718d7a3ce595f289bfee26adc178f5 # Proper/Repack
          - ae43b294509409a6a13919dedd4764c4 # Repack2
          - 5caaaa1c08c1742aa4342d8c4cc463f2 # Repack3
          # - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          # - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          # - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          # - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          # - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          # - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: HD Bluray + WEB

      - trash_ids:
          # Uncomment the next six lines to allow x265 HD releases with HDR/DV
          - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
        assign_scores_to:
          - name: HD Bluray + WEB
            score: 0
      - trash_ids:
          - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
        assign_scores_to:
          - name: HD Bluray + WEB

      # ===== Language =====
      - trash_ids:
          - 0542a48746585dc4444bbbb8a6bdf6ea # Language: Original + French
        assign_scores_to:
          - name: HD Bluray + WEB
            score: 500
      - trash_ids:
          - d6e9318c875905d6cfb5bee961afcea9 # Language: Not Original
        assign_scores_to:
          - name: HD Bluray + WEB
            score: -10000
      - trash_ids:
          - 533f782474f0819643c2ec0c1eeeb0ac # Language: Not French
        assign_scores_to:
          - name: HD Bluray + WEB
            score: 0
      - trash_ids:
          - 9172b2f683f6223e3a1846427b417a3d # VOSTFR
        assign_scores_to:
          - name: HD Bluray + WEB
            score: 0

      - trash_ids:
          # ===== HQ Release Groups =====
          - 5322da05b19d857acc1e75be3edf47b3 # FR HD Bluray Tier 01
          - 57f34251344be2e283fc30e00e458be6 # FR HD Bluray Tier 02
          - 9790a618cec1aeac8ce75601a17ea40d # FR WEB Tier 01
          - 3c83a765f84239716bd5fd2d7af188f9 # FR WEB Tier 02
          - 0d94489c0d5828cd3bf9409d309fb32b # FR Scene Groups
          - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
          - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
          - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
        assign_scores_to:
          - name: HD Bluray + WEB
