# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  sonarr:
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    media_naming:
      series: plex
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    include:
      # Comment out any of the following includes to disable them
      - template: sonarr-quality-definition-series
      # - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-quality-profile-web-2160p-alternative
      - template: sonarr-v4-custom-formats-web-2160p
      # - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-quality-profile-web-1080p-alternative
      - template: sonarr-v4-custom-formats-web-1080p
    custom_formats:
      # =================================
      # WEB-2160p
      # =================================
      # HDR Formats
      - trash_ids:
          # Comment out the next line if you and all of your users' setups are fully DV compatible
          # - 9b27ab6498ec0f31a3353992e19434ca # DV (WEBDL)

          # HDR10+ Boost - Uncomment the next two lines if any of your devices DO support HDR10+
          - 0dad0a507451acddd754fe6dc3a7f5e7 # HDR10+ Boost
          - 385e9e8581d33133c3961bdcdeffb7b4 # DV HDR10+ Boost
        assign_scores_to:
          - name: WEB-2160p

      # Optional
      - trash_ids:
          # - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          # - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          # - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          # - 06d66ab109d4d2eddb2794d21526d140 # Retags
          # - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-2160p

      - trash_ids:
          # Uncomment the next six lines to allow x265 HD releases with HDR/DV
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        assign_scores_to:
          - name: WEB-2160p
            score: 0
      - trash_ids:
          - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: WEB-2160p

      # Optional SDR
      # Only ever use ONE of the following custom formats:
      # SDR - block ALL SDR releases
      # SDR (no WEBDL) - block UHD/4k Remux and Bluray encode SDR releases, but allow SDR WEB
      - trash_ids:
          # - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR
          - 83304f261cf516bb208c18c54c0adf97 # SDR (no WEBDL)
        assign_scores_to:
          - name: WEB-2160p

      # =================================
      # WEB-1080p
      # =================================
      # Optional
      - trash_ids:
          # - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          # - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          # - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          # - 06d66ab109d4d2eddb2794d21526d140 # Retags
          # - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-1080p

      - trash_ids:
          # Uncomment the next six lines to allow x265 HD releases with HDR/DV
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        assign_scores_to:
          - name: WEB-1080p
            score: 0
      - trash_ids:
          - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: WEB-1080p


      # =================================
      # SHARED
      # =================================
      - trash_ids:
          - 0542a48746585dc4444bbbb8a6bdf6ea # Language: Original + French
        assign_scores_to:
          - name: WEB-2160p
            score: 500
          - name: WEB-1080p
            score: 500
      - trash_ids:
          - d6e9318c875905d6cfb5bee961afcea9 # Language: Not Original
        assign_scores_to:
          - name: WEB-2160p
            score: -10000
          - name: WEB-1080p
            score: 500
      - trash_ids:
          - 533f782474f0819643c2ec0c1eeeb0ac # Language: Not French
        assign_scores_to:
          - name: WEB-2160p
            score: 0
          - name: WEB-1080p
            score: 500
      - trash_ids:
          - 9172b2f683f6223e3a1846427b417a3d # VOSTFR
        assign_scores_to:
          - name: WEB-2160p
            score: 0
          - name: WEB-1080p
            score: 500

      - trash_ids:
          # ===== HQ Release Groups =====
          - 5322da05b19d857acc1e75be3edf47b3 # FR HD Bluray Tier 01
          - 57f34251344be2e283fc30e00e458be6 # FR HD Bluray Tier 02
          - 9790a618cec1aeac8ce75601a17ea40d # FR WEB Tier 01
          - 3c83a765f84239716bd5fd2d7af188f9 # FR WEB Tier 02
          - dbfc0a4b5cb4cbd693311c4482ae9683 # FR WEB Tier 03
          - 0d94489c0d5828cd3bf9409d309fb32b # FR Scene Groups
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
        assign_scores_to:
          - name: WEB-2160p
          - name: WEB-1080p
