# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
###################################################################################################
# Recyclarr Configuration Template: FR-BLURAY-WEB-1080p (V4)                                      #
# Updated: 2024-12-03                                                                             #
# Documentation: https://recyclarr.dev                                                            #
# Note: The following will be in French but hold basically the same info as the other template    #
# ----------------------------------------------------------------------------------------------- #
# Si vous utilisez plusieurs profiles dans une seule instance merci de vous référez               #
# à la documentation suivante (en anglais) pour les combiner :                                    #
# https://recyclarr.dev/wiki/yaml/config-examples/#merge-single-instance                          #
# Cette config est valable seulement pour la version 4 de Sonarr                                  #
###################################################################################################

# Definition d'une instance : https://recyclarr.dev/wiki/yaml/config-reference/basic/
sonarr:
  sonarr2:
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    media_naming:
      series: plex
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    include:
      # - template: sonarr-quality-definition-anime
      # Profile souhaité - veuillez à avoir les lignes correspondantes activées
      # --- Profile VOSTFR ---
      - template: sonarr-v4-quality-profile-1080p-french-anime-vostfr
      - template: sonarr-v4-custom-formats-1080p-french-anime-vostfr
      # --- Profile MULTi.VO ---
      - template: sonarr-v4-quality-profile-1080p-french-anime-multi
      - template: sonarr-v4-custom-formats-1080p-french-anime-multi

    # Formats Personnalisés (Custom Formats) :
    # https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Décommenter le score associé si vous préférez les groupes de FanSUB.
      - trash_ids:
          - 44b6c964dad997577d793fd004a39224  # FR Anime FanSub
        assign_scores_to:
          # - name: FR-ANIME-VOSTFR
            # score: 1700
          # - name: FR-ANIME-MULTi
            # score: 1700

      # Décommenter le score associé si vous ne voulez pas de FanSUB.
      - trash_ids:
          - 84f0acbda9c0c9de783894fb66df25aa  # FanSUB
        assign_scores_to:
          # - name: FR-ANIME-VOSTFR
            # score: -10000
          # - name: FR-ANIME-MULTi
            # score: -10000

      # Ajuster le score comme souhaité pour les Formats Personnalisés suivant
      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
        assign_scores_to:
          - name: FR-ANIME-VOSTFR
            score: 10 # Ajuster le score comme souhaité
          - name: FR-ANIME-MULTi
            score: 10 # Ajuster le score comme souhaité
      - trash_ids:
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
        assign_scores_to:
          - name: FR-ANIME-VOSTFR
            score: 10 # Ajuster le score comme souhaité
          - name: FR-ANIME-MULTi
            score: 10 # Ajuster le score comme souhaité
      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        assign_scores_to:
          - name: FR-ANIME-VOSTFR
            score: 10 # Ajuster le score comme souhaité
          - name: FR-ANIME-MULTi
            score: 10 # Ajuster le score comme souhaité
