# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  sonarr:
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    quality_definition:
      type: series
    media_naming:
      series: plex
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    include:
      # Comment out any of the following includes to disable them
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-custom-formats-web-2160p
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime
    custom_formats:
      # =================================
      # WEB-2160p
      # =================================
      # HDR Formats
      - trash_ids:
          # Comment out the next line if you and all of your users' setups are fully DV compatible
          # - 9b27ab6498ec0f31a3353992e19434ca # DV (WEBDL)

          # HDR10+ Boost - Uncomment the next two lines if any of your devices DO support HDR10+
          - 0dad0a507451acddd754fe6dc3a7f5e7 # HDR10+ Boost
          - 385e9e8581d33133c3961bdcdeffb7b4 # DV HDR10+ Boost
        quality_profiles:
          - name: WEB-2160p

      # Optional
      - trash_ids:
          # - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          # - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          # - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          # - 06d66ab109d4d2eddb2794d21526d140 # Retags
          # - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        quality_profiles:
          - name: WEB-2160p

      - trash_ids:
          # Uncomment the next six lines to allow x265 HD releases with HDR/DV
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        quality_profiles:
          - name: WEB-2160p
            score: 0
      - trash_ids:
          - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        quality_profiles:
          - name: WEB-2160p

      # Optional SDR
      # Only ever use ONE of the following custom formats:
      # SDR - block ALL SDR releases
      # SDR (no WEBDL) - block UHD/4k Remux and Bluray encode SDR releases, but allow SDR WEB
      - trash_ids:
          # - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR
          - 83304f261cf516bb208c18c54c0adf97 # SDR (no WEBDL)
        quality_profiles:
          - name: WEB-2160p


      # =================================
      # WEB-1080p
      # =================================
      # Optional
      - trash_ids:
          # - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          # - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          # - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          # - 06d66ab109d4d2eddb2794d21526d140 # Retags
          # - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        quality_profiles:
          - name: WEB-1080p

      - trash_ids:
          # Uncomment the next six lines to allow x265 HD releases with HDR/DV
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        quality_profiles:
          - name: WEB-1080p
            score: 0
      - trash_ids:
          - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        quality_profiles:
          - name: WEB-1080p

      # =================================
      # Remux-1080p - Anime
      # =================================
      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 10
