commands:
  recheck: False
  cat_update: False
  tag_update: True
  rem_unregistered: False # Plan to change to true in the future
  tag_tracker_error: True
  rem_orphaned: True
  tag_nohardlinks: True
  share_limits: True
  skip_qb_version_check: False
  skip_cleanup: False

qbt:
  host: !ENV QBT_HOST
  user: !ENV QBT_USER
  pass: !ENV QBT_PASS

settings:
  force_auto_tmm: False # Will force qBittorrent to enable Automatic Torrent Management for each torrent.
  force_auto_tmm_ignore_tags: [] #Torrents with these tags will be ignored when force_auto_tmm is enabled.
  tracker_error_tag: tracker_issue # Will set the tag of any torrents that do not have a working tracker.
  nohardlinks_tag: no_hardlinks # Will set the tag of any torrents with no hardlinks.
  stalled_tag: stalled # Will set the tag of any torrents stalled downloading.
  share_limits_tag: ~limit # Will add this tag when applying share limits to provide an easy way to filter torrents by share limit group/priority for each torrent
  share_limits_min_seeding_time_tag: MinSeedTimeNotReached # Tag to be added to torrents that have not yet reached the minimum seeding time
  share_limits_min_num_seeds_tag: MinSeedsNotMet # Tag to be added to torrents that have not yet reached the minimum number of seeds
  share_limits_last_active_tag: LastActiveLimitNotReached # Tag to be added to torrents that have not yet reached the last active limit
  cat_filter_completed: True # Filters for completed torrents only when running cat_update command
  share_limits_filter_completed: False # Filters for completed torrents only when running share_limits command
  tag_nohardlinks_filter_completed: True # Filters for completed torrents only when running tag_nohardlinks command
  rem_unregistered_filter_completed: False # Filters for completed torrents only when running rem_unregistered command
  cat_update_all: True # Checks and updates all torrent categories if set to True when running cat_update command, otherwise only update torrents that are uncategorized
  disable_qbt_default_share_limits: True # Allows QBM to handle share limits by disabling qBittorrents default Share limits. Only active when the share_limits command is set to True
  tag_stalled_torrents: True # Tags any downloading torrents that are stalled with the `stalledDL` tag when running the tag_update command
  rem_unregistered_ignore_list: [] # Ignores a list of words found in the status of the tracker when running rem_unregistered command and will not remove the torrent if matched

directory:
  root_dir: "/home/siffreinsg/downloads/qbittorrent"
  remote_dir: "/home/siffreinsg/downloads/qbittorrent"
  recycle_bin: "/home/siffreinsg/downloads/qbittorrent/.Trash"
  torrents_dir: "/home/siffreinsg/.local/share/qBittorrent/BT_backup"
  orphaned_dir: "/home/siffreinsg/downloads/qbittorrent/orphaned"

cat:
  radarr: /home/siffreinsg/downloads/qbittorrent/radarr
  radarr-completed: /home/siffreinsg/downloads/qbittorrent/radarr-completed
  radarr-sqp: /home/siffreinsg/downloads/qbittorrent/radarr-sqp
  radarr-sqp-completed: /home/siffreinsg/downloads/qbittorrent/radarr-sqp-completed
  sonarr: /home/siffreinsg/downloads/qbittorrent/sonarr
  sonarr-completed: /home/siffreinsg/downloads/qbittorrent/sonarr-completed
  sonarr2: /home/siffreinsg/downloads/qbittorrent/sonarr2
  sonarr2-completed: /home/siffreinsg/downloads/qbittorrent/sonarr2-completed
  prowlarr: /home/siffreinsg/downloads/qbittorrent/prowlarr
  qbittorrent: /home/siffreinsg/downloads/qbittorrent/
  # Uncategorized: /home/siffreinsg/downloads/qbittorrent/

tracker:
  # Private trackers
  maxp2p|p2p-world|drago-tracker:
    tag: [private, ygg]
  sharewood.tv:
    tag: [private, sharewood.tv]
  upload.cx:
    tag: [private, upload.cx]
  milkie:
    tag: [private, milkie]
  torrentleech|tleechreload:
    tag: [private, torrentleech]
  # Public trackers
  other:
    tag: [public]

nohardlinks:
  radarr-completed:
  radarr-sqp-completed:
  sonarr-completed:
  sonarr2-completed:

share_limits:
  # Seed torrents with no hardlinks
  private_no_hardlinks: # From private trackers
    priority: 1
    include_all_tags: [no_hardlinks, private]
    categories:
      - radarr-completed
      - radarr-sqp-completed
      - sonarr-completed
      - sonarr2-completed
    max_ratio: -1
    max_seeding_time: 30d
    max_last_active: 30d
    min_last_active: 1d # Keep seeding if the torrent has been active in the last day
    cleanup: true
  no_hardlinks: # From all trackers
    priority: 5
    include_all_tags: [no_hardlinks]
    exclude_any_tags: [private]
    categories:
      - radarr-completed
      - radarr-sqp-completed
      - sonarr-completed
      - sonarr2-completed
    max_ratio: 0
    max_seeding_time: 7d
    max_last_active: 7d
    limit_upload_speed: 0
    cleanup: true
  # Private trackers
  private:
    priority: 25
    include_all_tags: [private]
    max_ratio: -1
    max_seeding_time: -1
    max_last_active: -1
    limit_upload_speed: -1
    cleanup: false
  # Public trackers
  default:
    priority: 999
    max_seeding_time: 0s
    limit_upload_speed: 0

recyclebin:
  enabled: true
  empty_after_x_days: 30
  save_torrents: true
  split_by_category: true

orphaned:
  empty_after_x_days: 30
  exclude_patterns:
    - "**/.DS_Store"
    - "**/Thumbs.db"
    - "**/@eaDir"
    - "/data/torrents/temp/**"
    - "**/*.!qB"
    - "**/*_unpackerred"
  max_orphaned_files_to_delete: 10
  min_file_age_minutes: 0

webhooks:
  error: !ENV QBM_WEBHOOK_ERROR
  run_start: !ENV QBM_WEBHOOK_RUN_START
  run_end: !ENV QBM_WEBHOOK_RUN_END
  function:
    recheck: !ENV QBM_WEBHOOK_RECHECK
    cat_update: !ENV QBM_WEBHOOK_CAT_UPDATE
    tag_update: !ENV QBM_WEBHOOK_TAG_UPDATE
    rem_unregistered: !ENV QBM_WEBHOOK_REM_UNREGISTERED
    tag_tracker_error: !ENV QBM_WEBHOOK_TAG_TRACKER_ERROR
    rem_orphaned: !ENV QBM_WEBHOOK_REM_ORPHANED
    tag_nohardlinks: !ENV QBM_WEBHOOK_TAG_NOHARDLINKS
    share_limits: !ENV QBM_WEBHOOK_SHARE_LIMITS
    cleanup_dirs: !ENV QBM_WEBHOOK_CLEANUP_DIRS
