# https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup

commands:
  dry_run: false # Will not execute any commands, but will print what would be executed.
  recheck: false # Will recheck all torrents.
  cat_update: true # Will update torrent categories.
  tag_update: true # Will update torrent tags.
  rem_unregistered: true # Will remove torrents that are not registered with qBittorrent.
  tag_tracker_error: true # Will tag torrents that have a tracker error.
  rem_orphaned: true # Will remove orphaned data.
  tag_nohardlinks: true # Will tag torrents that have no hardlinks.
  share_limits: true # Will apply share limits to torrents.
  skip_qb_version_check: true # Will skip checking qBittorrent version.
  skip_cleanup: false # Use this to skip emptying the Recycle Bin folder

qbt:
  host: !ENV QBT_HOST # Change to your qBittorrent host
  user: !ENV QBT_USER # Change to your qBittorrent username or leave empty if IP whitelisted
  pass: !ENV QBT_PASS # Change to your qBittorrent password or leave empty if IP whitelisted

settings:
  force_auto_tmm: true # Will force qBittorrent to enable Automatic Torrent Management for each torrent.
  force_auto_tmm_ignore_tags: #Torrents with these tags will be ignored when force_auto_tmm is enabled.
    - cross-seed
    - Upload
  tracker_error_tag: issue # Will set the tag of any torrents that do not have a working tracker.
  nohardlinks_tag: noHL # Will set the tag of any torrents with no hardlinks.
  stalled_tag: stalledDL # Will set the tag of any torrents stalled downloading.
  share_limits_tag: ~share_limit # Will add this tag when applying share limits to provide an easy way to filter torrents by share limit group/priority for each torrent
  share_limits_min_seeding_time_tag: MinSeedTimeNotReached # Tag to be added to torrents that have not yet reached the minimum seeding time
  share_limits_min_num_seeds_tag: MinSeedsNotMet # Tag to be added to torrents that have not yet reached the minimum number of seeds
  share_limits_last_active_tag: LastActiveLimitNotReached # Tag to be added to torrents that have not yet reached the last active limit
  cat_filter_completed: True # Filters for completed torrents only when running cat_update command
  share_limits_filter_completed: True # Filters for completed torrents only when running share_limits command
  tag_nohardlinks_filter_completed: True # Filters for completed torrents only when running tag_nohardlinks command
  rem_unregistered_filter_completed: False # Filters for completed torrents only when running rem_unregistered command
  cat_update_all: True # Checks and updates all torrent categories if set to True when running cat_update command, otherwise only update torrents that are uncategorized
  disable_qbt_default_share_limits: True # Allows QBM to handle share limits by disabling qBittorrents default Share limits. Only active when the share_limits command is set to True
  tag_stalled_torrents: True # Tags any downloading torrents that are stalled with the `stalledDL` tag when running the tag_update command
  rem_unregistered_ignore_list: # Ignores a list of words found in the status of the tracker when running rem_unregistered command and will not remove the torrent if matched
    - example placeholder words
    - ignore if found

directory:
  # Do not remove these
  # root_dir var: </your/path/here/>  # Root downloads directory used to check for orphaned files, noHL, and RecycleBin.
  # <OPTIONAL> remote_dir var: </your/path/here/>  # Path of docker host mapping of root_dir.
  # remote_dir must be set if you're running qbit_manage locally and qBittorrent/cross_seed is in a docker
  # remote_dir should not be set if qbit_manage is running in a container
  # <OPTIONAL> recycle_bin var: </your/path/here/>   # Path of the RecycleBin folder. Default location is set to remote_dir/.RecycleBin
  # <OPTIONAL> torrents_dir var: </your/path/here/>  # Path of the your qbittorrent torrents directory. Required for `save_torrents` attribute in recyclebin
  # <OPTIONAL> orphaned_dir var: </your/path/here/>  # Path of the the Orphaned Data folder. This is similar to RecycleBin, but only for orphaned data.
  root_dir: /home/siffreinsg/downloads/qbittorrent
  remote_dir: /home/siffreinsg/downloads/qbittorrent
  torrents_dir: /home/siffreinsg/.local/share/qBittorrent/BT_backup
  # recycle_bin: "/home/siffreinsg/downloads/qbittorrent/.RecycleBin"
  orphaned_dir: /home/siffreinsg/downloads/qbittorrent/orphaned_data


cat:
  radarr: /home/siffreinsg/downloads/qbittorrent/radarr
  radarr-sqp: /home/siffreinsg/downloads/qbittorrent/radarr-sqp
  sonarr: /home/siffreinsg/downloads/qbittorrent/sonarr
  sonarr2: /home/siffreinsg/downloads/qbittorrent/sonarr2
  prowlarr: /home/siffreinsg/downloads/qbittorrent/prowlarr
  qbittorrent: /home/siffreinsg/downloads/qbittorrent/

cat_change:

tracker:
  joinpeers|loadpeers|drago-server|drago-tracker|maxp2p:
    tag:
      - private
      - yggtorrent
  sharewood.tv:
    tag:
      - private
      - sharewood
  upload.cx:
    tag:
      - private
      - uploadcx
  digitalcore:
    tag:
      - private
      - digitalcore
  tlzdigital.com:
    tag:
      - private
      - tlzdigital
  other:
    tag:
      - public

nohardlinks:
  - radarr-completed
  - radarr-sqp-completed
  - sonarr-completed
  - sonarr2-completed

share_limits:
  # =====================
  # Torrents with noHL tag (from *arr)
  # =====================
  noHL_private: # Delete private torrents after 7 days of seeding
    priority: 1
    include_all_tags:
      - noHL
      - private
    max_ratio: 1
    max_seeding_time: 10080 # 7 days
    cleanup: true

  noHL_public: # Delete public torrents immediately
    priority: 2
    include_all_tags:
      - noHL
      - public
    max_ratio: 0
    max_seeding_time: 0
    cleanup: true
  # =====================
  # Torrents from *arr
  # =====================
  arr_private:
    priority: 10
    include_all_tags:
      - private
    categories:
      - radarr-completed
      - radarr-sqp-completed
      - sonarr-completed
      - sonarr2-completed
      - radarr
      - radarr-sqp
      - sonarr
      - sonarr2
    cleanup: false
    max_ratio: -1
    max_seeding_time: -1

  arr_public:
    priority: 15
    include_all_tags:
      - public
    categories:
      - radarr-completed
      - radarr-sqp-completed
      - sonarr-completed
      - sonarr2-completed
      - radarr
      - radarr-sqp
      - sonarr
      - sonarr2
    max_ratio: 0
    max_seeding_time: 0
    limit_upload_speed: 0
    cleanup: true
  # =====================
  # Manual torrents
  # =====================
  manual_private:
    priority: 20
    include_all_tags:
      - private
    categories:
      - qbittorrent
      - prowlarr
    max_ratio: -1
    max_seeding_time: -1
    cleanup: false

  manual_public:
    priority: 25
    include_all_tags:
      - public
    categories:
      - qbittorrent
      - prowlarr
    max_ratio: 0
    max_seeding_time: 0
    limit_upload_speed: 0
    cleanup: false
  # =====================
  # Other torrents
  # =====================
  default:
    priority: 999
    max_ratio: -1
    max_seeding_time: -1
    cleanup: false

recyclebin:
  enabled: false
  empty_after_x_days: 7
  save_torrents: true
  split_by_category: true

orphaned:
  empty_after_x_days: 14
  exclude_patterns:
    - '**/.DS_Store'
    - '**/Thumbs.db'
    - '**/@eaDir'
    - '**/temp/**'
    - '**/*.!qB'
    - '**/*_unpackerred'

webhooks:
  error: !ENV QBM_WEBHOOK_ERROR
  run_start: !ENV QBM_WEBHOOK_RUN_START
  run_end: !ENV QBM_WEBHOOK_RUN_END
  function:
    recheck: !ENV QBM_WEBHOOK_RECHECK
    cat_update: !ENV QBM_WEBHOOK_CAT_UPDATE
    tag_update: !ENV QBM_WEBHOOK_TAG_UPDATE
    rem_unregistered: !ENV QBM_WEBHOOK_REM_UNREGISTERED
    tag_tracker_error: !ENV QBM_WEBHOOK_TAG_TRACKER_ERROR
    rem_orphaned: !ENV QBM_WEBHOOK_REM_ORPHANED
    tag_nohardlinks: !ENV QBM_WEBHOOK_TAG_NOHARDLINKS
    share_limits: !ENV QBM_WEBHOOK_SHARE_LIMITS
    cleanup_dirs: !ENV QBM_WEBHOOK_CLEANUP_DIRS
