- label: bazarr
  display_name: Bazarr
  repo: linuxserver/docker-bazarr
  target_commitish: master
- label: filebrowser
  display_name: File Browser
  repo: filebrowser/filebrowser
  target_commitish: master
- label: overseerr
  display_name: Overseerr
  repo: linuxserver/docker-overseerr
  target_commitish: main
- label: plex
  display_name: Plex
  repo: linuxserver/docker-plex
  target_commitish: master
- label: prowlarr
  display_name: Prowlarr
  repo: linuxserver/docker-prowlarr
  target_commitish: main
- label: radarr
  display_name: Radarr
  repo: linuxserver/docker-radarr
  target_commitish: master
- label: sonarr
  display_name: Sonarr
  repo: linuxserver/docker-sonarr
  target_commitish: develop
- label: syncthing
  display_name: Syncthing
  repo: linuxserver/docker-syncthing
  target_commitish: master
- label: tautulli
  display_name: Tautulli
  repo: linuxserver/docker-tautulli
  target_commitish: master
- label: recyclarr
  display_name: Recyclarr
  repo: recyclarr/recyclarr
  target_commitish: master
- label: vuetorrent
  display_name: VueTorrent
  repo: WDaan/VueTorrent
- label: qbit_manage
  display_name: qBit Manage
  repo: StuffAnThings/qbit_manage
  target_commitish: master
- label: Plex-Auto-Languages
  display_name: Plex Auto Languages
  repo: RemiRigal/Plex-Auto-Languages
  target_commitish: master
